# Write your MySQL query statement below
SELECT R.CONTEST_ID,
ROUND(COUNT(DISTINCT U.USER_ID) * 100 / (SELECT COUNT(*) FROM USERS),2) AS PERCENTAGE
FROM USERS U
JOIN REGISTER R ON R.USER_ID = U.USER_ID
GROUP BY R.CONTEST_ID
ORDER BY PERCENTAGE DESC, R.CONTEST_ID