# Write your MySQL query statement below
-- SELECT 
-- VISITS.CUSTOMER_ID,
-- COUNT(*) AS COUNT_NO_TRANS 
-- FROM VISITS 
-- LEFT JOIN TRANSACTIONS USING (VISIT_ID)
-- WHERE TRANSACTIONS.TRANSACTION_ID IS NULL
-- GROUP BY VISITS.CUSTOMER_ID;

SELECT CUSTOMER_ID, COUNT(1) AS COUNT_NO_TRANS
FROM VISITS 
WHERE VISIT_ID NOT IN (
        SELECT VISIT_ID FROM TRANSACTIONS)
GROUP BY 1;