# Write your MySQL query statement below
SELECT P.PROJECT_ID, 
ROUND(AVG(E.EXPERIENCE_YEARS),2) AS AVERAGE_YEARS
FROM EMPLOYEE E
INNER JOIN PROJECT P ON P.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY P.PROJECT_ID